version: 2

jobs:
  checkout_and_compile:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    working_directory: ~/set-protocol-v2
    steps:
      - checkout
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - run:
          name: Fetch Dependencies
          command: yarn install
      - save_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Transpile Contracts
          command: yarn build
      - save_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/set-protocol-v2
  test:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/set-protocol-v2
    steps:
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - run:
          name: Re-compile for HardhatEVM
          command: yarn compile
      - run:
          name: Test RPC
          command: yarn chain
          background: true
      - run:
          name: Hardhat Test
          command: yarn test:fast

  test_ovm:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    working_directory: ~/set-protocol-v2
    steps:
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - run:
          name: Clone eth-optimism/optimism
          command: |
            git clone https://github.com/ethereum-optimism/optimism.git
      - run:
          name: Docker ghcr.io login
          command: |
            docker login ghcr.io -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Install Optimism client
          command: |
            cd optimism
            git checkout dee74ef54b38750085a8cc2dfbcb67dc80d2a10f
            cp ../scripts/optimism/docker-compose.yml ./ops/docker-compose.yml
            cd ops
            docker-compose pull
      - run:
          name: Launch Optimism client
          command: |
            cd optimism
            git checkout dee74ef54b38750085a8cc2dfbcb67dc80d2a10f
            cd ops
            docker-compose up -d && ./scripts/wait-for-sequencer.sh
            wget \
              --retry-connrefused \
              --waitretry=1 \
              --read-timeout=120 \
              --timeout=120 \
              -t 100 \
              http://localhost:8545
      - run:
          name: Test
          command: |
            yarn ovm:fundl2EthAccounts
            yarn test:ovm:fast test/protocol/core.spec.ts


workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_and_compile
      - test:
          requires:
            - checkout_and_compile
      - test_ovm:
          requires:
            - checkout_and_compile
