version: 2

jobs:
  install:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/set-protocol-v2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - run:
          name: Fetch Dependencies
          command: yarn install
      - save_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Transpile Contracts
          command: yarn build
      - save_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/set-protocol-v2

  test_ovm:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/set-protocol-v2
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env

      # TODO....

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_and_compile
      - test_ovm:
          requires:
            - checkout_and_compile
